In [6]:
import torch
import torch.nn as nn

In [7]:
torch.manual_seed(42)

In [12]:
n,d = 10, 3
embedding_layer = nn.Embedding(num_embeddings= n, embedding_dim= d)

embedding_layer.weight

Parameter containing:
tensor([[ 0.4048, -1.3543, -0.4976],
        [ 0.4747, -2.5095,  0.4880],
        [ 0.7846,  0.0286,  1.7423],
        [-1.3527,  0.2191,  0.5526],
        [-0.1853,  0.7528,  1.0131],
        [-0.3308,  0.5177,  0.3878],
        [-0.5797, -0.1691,  1.9312],
        [ 1.0119, -0.4752, -0.4920],
        [ 0.2704, -0.5628,  0.6793],
        [ 0.4405,  1.1415,  0.0186]], requires_grad=True)

In [18]:
input = torch.tensor([[1,2,4,5,6], 
                      [4,3,2,9,5]])
input

tensor([[1, 2, 4, 5, 6],
        [4, 3, 2, 9, 5]])

In [19]:
output = embedding_layer(input)
output

tensor([[[ 0.4747, -2.5095,  0.4880],
         [ 0.7846,  0.0286,  1.7423],
         [-0.1853,  0.7528,  1.0131],
         [-0.3308,  0.5177,  0.3878],
         [-0.5797, -0.1691,  1.9312]],

        [[-0.1853,  0.7528,  1.0131],
         [-1.3527,  0.2191,  0.5526],
         [ 0.7846,  0.0286,  1.7423],
         [ 0.4405,  1.1415,  0.0186],
         [-0.3308,  0.5177,  0.3878]]], grad_fn=<EmbeddingBackward0>)