In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.randn(1,3,224,224) # input image
x

tensor([[[[-0.3691, -0.0681, -1.0872,  ...,  1.7887,  0.6176,  0.9026],
          [ 0.1702,  0.0927, -1.2326,  ...,  1.2595,  1.5337,  1.0712],
          [-0.3475, -1.1623, -0.7536,  ...,  1.3126,  1.3199,  1.1231],
          ...,
          [ 0.5489, -0.4120,  2.6624,  ..., -0.6737, -0.3856,  0.9177],
          [-0.5326,  0.6732, -0.9524,  ..., -0.3519,  1.1474,  0.3075],
          [-1.1327, -0.0208, -1.3903,  ...,  1.2329,  1.6409, -1.6023]],

         [[-0.3833,  1.3292,  0.2403,  ...,  1.1055, -1.2568,  0.0837],
          [ 0.7942,  2.1096, -1.4896,  ..., -0.3515,  0.7250,  0.4499],
          [-0.2160,  0.6669, -0.3711,  ..., -0.7572,  1.2601,  0.5764],
          ...,
          [ 1.2299,  1.9516,  0.3311,  ...,  0.8916, -0.0746, -0.9498],
          [ 0.6494, -0.3620, -0.1426,  ..., -0.3440, -0.0194, -0.2656],
          [ 0.6403, -2.3602,  0.6984,  ...,  0.3907, -0.2724, -1.4895]],

         [[ 1.2454, -1.3870,  0.0563,  ...,  0.9946, -1.3066, -1.0536],
          [ 0.7112,  0.9290, -

In [5]:
# using conv2d approach
patch_embed = nn.Conv2d(in_channels= 3,
                        out_channels= 768,
                        kernel_size=16,
                        stride=16)

# (1,3,224,224) -> (1,768,14,14)
x = patch_embed(x)
x

tensor([[[[-6.2984e-01,  3.3374e-01, -1.0985e+00,  ...,  9.4188e-01,
           -4.9088e-02, -1.3377e-01],
          [ 5.0515e-01,  6.4522e-01, -1.2597e+00,  ..., -2.4301e-01,
           -6.6457e-02, -6.3281e-01],
          [ 5.0594e-01,  7.9543e-02, -4.2748e-01,  ...,  6.4184e-01,
           -1.1725e+00,  1.1414e+00],
          ...,
          [-2.8341e-01,  2.6394e-01, -4.5672e-01,  ...,  6.3873e-01,
           -6.8420e-01, -1.0217e+00],
          [-1.4557e-01, -1.0023e-01,  6.0208e-01,  ...,  3.3988e-01,
            7.8355e-02,  1.2167e-02],
          [ 2.9010e-01, -2.3099e-01,  8.2119e-02,  ..., -8.4183e-03,
           -5.5140e-01,  1.6553e-01]],

         [[-1.2053e-01,  1.0412e+00, -9.7092e-02,  ...,  3.4580e-01,
            6.5758e-01,  2.3192e-02],
          [-7.7227e-02, -3.0925e-01,  2.5199e-01,  ..., -1.6480e-01,
            9.1610e-01,  7.6756e-02],
          [ 1.5163e-01,  6.2517e-01,  6.5205e-01,  ..., -2.7943e-01,
            1.0151e+00, -8.4929e-01],
          ...,
     

In [7]:
# (1,768,14,14) -> (1,768,196)
x = x.flatten(2)
x

tensor([[[-0.6298,  0.3337, -1.0985,  ..., -0.0084, -0.5514,  0.1655],
         [-0.1205,  1.0412, -0.0971,  ..., -0.5725, -0.4812, -1.0483],
         [ 0.7878, -1.1406,  0.0245,  ...,  1.0324,  1.0120, -0.2369],
         ...,
         [ 0.1545, -0.1188, -0.9192,  ...,  0.2376,  0.6752, -0.2803],
         [-0.9972, -0.4206,  0.4035,  ...,  0.2824,  0.6632, -0.4898],
         [ 1.3826, -0.5749,  0.4210,  ...,  0.8795,  0.9122, -0.5577]]],
       grad_fn=<ViewBackward0>)

# Now each of the 196 patches has been transformed into a 768-dimensional embedding vector

In [8]:
# (1,768,196) -> (1, 196, 768)
x = x.transpose(1,2)
x

tensor([[[-0.6298, -0.1205,  0.7878,  ...,  0.1545, -0.9972,  1.3826],
         [ 0.3337,  1.0412, -1.1406,  ..., -0.1188, -0.4206, -0.5749],
         [-1.0985, -0.0971,  0.0245,  ..., -0.9192,  0.4035,  0.4210],
         ...,
         [-0.0084, -0.5725,  1.0324,  ...,  0.2376,  0.2824,  0.8795],
         [-0.5514, -0.4812,  1.0120,  ...,  0.6752,  0.6632,  0.9122],
         [ 0.1655, -1.0483, -0.2369,  ..., -0.2803, -0.4898, -0.5577]]],
       grad_fn=<TransposeBackward0>)