In [ ]:
import numpy as np

## matrices types

In [ ]:
# square and rect
S = np.random.randn(5,5)
R = np.random.randn(5,2)
S,R

(array([[ 1.39718601, -0.20994304,  0.46336117,  1.35771965,  1.36773024],
        [-1.22671345,  0.12806804,  1.37563302,  0.38840772,  0.04135552],
        [-0.61711683, -0.60555236,  1.00317245,  1.61626219, -0.79667679],
        [-1.00555624, -0.60151085, -2.47444932, -1.74087759,  1.37427948],
        [-0.23442492, -0.87932432,  0.24234451, -1.33255453, -1.39303964]]),
 array([[ 0.8535944 , -0.5330156 ],
        [ 0.30175969, -0.56754309],
        [ 1.21722513, -0.83116611],
        [-0.85981112,  0.39042856],
        [ 1.817528  ,  0.00267265]]))

In [ ]:
# identity
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# zeros
Z = np.zeros((5,5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#diagonal
D = np.diag([1,2,3,4,5])
D

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
#traingular matrix
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
U, L


(array([[-0.2980203 ,  1.08692083,  0.65959898,  1.06918599,  1.97330949],
        [ 0.        , -1.54096136, -2.28858887,  0.1959458 ,  0.302759  ],
        [ 0.        ,  0.        , -0.54249504,  0.01585184,  1.03524477],
        [ 0.        ,  0.        ,  0.        ,  1.20303965, -0.6305164 ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.16231409]]),
 array([[-0.2980203 ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.53569622, -1.54096136,  0.        ,  0.        ,  0.        ],
        [-0.44384703,  0.37466854, -0.54249504,  0.        ,  0.        ],
        [-0.23712797, -0.17025703,  0.79768807,  1.20303965,  0.        ],
        [-0.04574414, -0.69130976,  0.6977217 , -0.36621105,  0.16231409]]))

In [ ]:
# concatenate
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)#same no of rows
C


array([[-0.63315081,  2.37529911, -0.54831059, -0.41141615,  0.27332229,
        -0.76913553],
       [ 1.75162448, -1.37265013, -1.37443054, -1.0686263 ,  0.5590487 ,
        -1.15834366],
       [ 0.06164805,  0.55919178, -1.93060047,  1.38573008,  2.61666357,
        -1.69731349]])

## addition and subtraction

In [ ]:
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

sum = A+C
sum

array([[ 2.08079613,  0.07994471, -0.09781941, -1.86586229],
       [ 1.21948934,  0.22416227,  0.72561433,  2.19516033],
       [ 1.03168788,  0.38550376, -1.34973896,  0.04523148],
       [-1.37848473,  2.02722231,  1.03425512, -0.15093546],
       [ 1.35024707, -0.84031056,  0.30165295,  1.88514408]])

In [ ]:
# shifting a square matrix
l = 0.03
N = 5
D = np.random.randn(N,N)# original

Ds = D + l*np.eye(N)# shifted diagonal
D, Ds

(array([[-0.63206219, -0.52137203, -0.06270608, -0.4776584 , -1.64027548],
        [ 1.51315824,  0.64457072, -0.31886471, -0.16681034, -0.10139707],
        [ 0.80177224, -0.6535557 , -1.81742225,  0.60362372, -0.61467105],
        [ 0.11133012, -1.71577241,  0.04763415,  1.03647167,  0.59936159],
        [ 0.045159  ,  1.22189835, -0.12531926,  1.57802117, -0.47729405]]),
 array([[-0.60206219, -0.52137203, -0.06270608, -0.4776584 , -1.64027548],
        [ 1.51315824,  0.67457072, -0.31886471, -0.16681034, -0.10139707],
        [ 0.80177224, -0.6535557 , -1.78742225,  0.60362372, -0.61467105],
        [ 0.11133012, -1.71577241,  0.04763415,  1.06647167,  0.59936159],
        [ 0.045159  ,  1.22189835, -0.12531926,  1.57802117, -0.44729405]]))

## Matrix - scaler Multiplication

In [ ]:
M = np.random.randn(5,5)
s = 2

M*s

array([[ 0.10498935, -1.50933588, -0.10480804, -1.92982395, -0.4072068 ],
       [ 0.95798724, -0.33007146, -2.59248774,  1.3867808 ,  2.11184703],
       [ 0.40238259,  4.1727762 , -0.94819188, -0.67392678,  2.16585511],
       [-4.12274758, -0.96923943, -1.74604573, -4.44382275,  2.69667902],
       [ 0.99362147, -0.39578786,  0.38882782, -1.98074615, -1.05215592]])

## Transpose

In [ ]:
M = np.array([[1,2,3],
              [2,3,4]])
#np.transpose(M) # works even if M is multidimensional list
M.T , M.T.T # single and double transpose # works when M is numpy array


(array([[1, 2],
        [2, 3],
        [3, 4]]),
 array([[1, 2, 3],
        [2, 3, 4]]))

In [ ]:
# complex  matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C.T) # transpose
print(C.conjugate().T) # Hermition transpose
print(np.matrix(C).H) # convert to matrix object and then H

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]
[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]
[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]


## Diagonal and trace

In [ ]:
M = np.round( 6*np.random.randn(4,4) )
print(M)

#extract diagonal
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

#trace (sum of diagonal elements)
tr = np.trace(M)
#tr2 = sum( np.diag(M) )
tr

[[ -3. -10.   0. -11.]
 [ -7.  10.   2.   4.]
 [ -7. -12.  12.   1.]
 [  2.   6.  13.  -2.]]
[-3. 10. 12. -2.]
[[-3.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. 12.  0.]
 [ 0.  0.  0. -2.]]


17.0

### code challange: linearity of trace

In [ ]:
# tr(A) + tr(B) = tr(A+B)??
# tr(l*A) = l *tr(A)

A = np.random.randn(4,4)
B = np.random.randn(4,4)
print(A,B)

print(np.trace(A+B) - (np.trace(A) + np.trace(B))) #True

print(np.trace(12*A) - 12*np.trace(A)) # True

[[ 1.43461975 -0.38016891 -1.2887027   1.0243114 ]
 [ 1.49302189  0.87805511 -0.25476231  0.44261445]
 [-0.12823659 -1.93116537  0.39040775  0.59748422]
 [-0.94635778 -0.47598503 -0.35222043  0.87977298]] [[ 0.28810669 -0.84848287 -0.61099183 -0.52182958]
 [-0.56327263 -1.03711956 -0.32298719  1.01796434]
 [-0.0059479   1.50939915 -0.97373607 -0.87586035]
 [ 0.00289595 -0.19017115 -1.08233873  1.04656251]]
-4.440892098500626e-16
0.0


## Broadcast Matric arithmetic

In [ ]:
# create a matrix according to column or rows
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]
A, r, c

(array([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]]),
 [10, 20, 30, 40],
 [100, 200, 300])

In [ ]:
print(A+r)# broadcast on rows
#print(A+c)# broadcast on columns is only explicit
print(A+np.reshape(c,(len(c),1))) # first create column vector and then add

[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
