## Import

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import math

## Compute rank

In [ ]:
# create random matrix
A = np.random.randint(1,5,(5,4))
ranka = np.linalg.matrix_rank(A)
print(A)
print(ranka)

# create a matrix with last two column repeated
B = A
B[:,-1] = B[:,-2] # rank reducing method
rankb = np.linalg.matrix_rank(B)
print(B)
print(rankb)


[[1 3 2 4]
 [3 3 3 2]
 [3 1 1 2]
 [2 2 2 4]
 [2 2 4 3]]
4
[[1 3 2 2]
 [3 3 3 3]
 [3 1 1 1]
 [2 2 2 2]
 [2 2 4 4]]
3


In [ ]:
# adding noise to a rank deficient matrix

A = np.round(10*np.random.randn(4,4))

#reduce rank
A[:,-1] = A[:,-2]

#noise level
noiseamp = 0.001

# add the noise
B = A + noiseamp * np.random.randn(4,4)

#print rank
print('rank (w/o noise) = ',np.linalg.matrix_rank(A))
print('rank (with noise) = ',np.linalg.matrix_rank(B))


rank (w/o noise) =  3
rank (with noise) =  4


### code challenge: reduced rank matrix via mat mul

In [ ]:
#create a matrix with rank 4
A = np.random.randn(10,4)
B = np.random.randn(4,10)
C = A@B
print(C.shape)
print(np.linalg.matrix_rank(C))


#size 
m = 10
n = 10
r = 5 #change

A = np.random.randn(m,r) @ np.random.randn(r,n)
print(A.shape)
print(np.linalg.matrix_rank(A))#rank = min(m,n,r)


(10, 10)
4
(10, 10)
5


### Code challenge: Scaler multiplication and rank

In [ ]:
#test whether matrix rank is invariant to scaler multiplication ===> correct with one exception: mul by zero

#create two matrices
A = np.round(10*np.random.randn(5,5)) #Full rank matrix
B = np.round(10*np.random.randn(5,5)) #Reduced rank matrix
B[:,-2] = B[:,-1]


#create some scaler 
l = np.random.randint(1,10,1) # only 0 can change rank ===> 

#print rank
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))
print(np.linalg.matrix_rank(l*A))
print(np.linalg.matrix_rank(l*B)) #conclusion: with scaler mult. rank is unchanged. (ie, dimension is unchanged)
                                    # vector only stretch or compress, it doesnt change direction

#check whether rank(l*A) == (l*rank(A))
print(np.linalg.matrix_rank(l*A) == (l*np.linalg.matrix_rank(A))) #False

5
4
5
4
[False]


## Rank of A^TA and AA^T

In [ ]:
# matrix sizes
m = 14
n =  3

# create matrices
A = np.round( 10*np.random.randn(m,n) )
print(np.linalg.matrix_rank(A))


AtA = A.T@A
AAt = A@A.T

print(AtA.shape)
print(AAt.shape)

print(np.linalg.matrix_rank(AtA))
print(np.linalg.matrix_rank(AAt))

#conclusion: rank doesnot change 

3
(3, 3)
(14, 14)
3
3


### code challenge: rank of multiplied and summed matrices

In [ ]:
#rules: rank(A*B) <= min(rank(A),rank(B))
#       rank(A+B) <= rank(A) + rank(B)

A =np.round(10*np.random.randn(2,5))
B = np.random.randint(1,21,(2,5))
AtA = A.T@A #symmetric matrix (2*2)
BtB = B.T@B
print(A.T.shape)
print(B)

print(np.linalg.matrix_rank(AtA)) # 5x5 matrix
print(np.linalg.matrix_rank(BtB))

print((AtA + BtB).shape)
print(np.linalg.matrix_rank(AtA @ BtB)) # 5x5 matrix
print(np.linalg.matrix_rank(AtA + BtB)) # 5x5 matrix

print(np.linalg.matrix_rank(AtA @ BtB) <= min(np.linalg.matrix_rank(AtA),np.linalg.matrix_rank(BtB))) # True
print(np.linalg.matrix_rank(AtA+BtB) <= np.linalg.matrix_rank(AtA) + np.linalg.matrix_rank(BtB)) # True

(5, 2)
[[14  4 20  4 20]
 [ 6 13 14  4  3]]
2
2
(5, 5)
2
4
True
True


## Making a matrix full-rank by "shifting"

In [ ]:
#size
m = 30

# square symmetric matrix 
A = np.random.randn(m,m)
A = np.round(10 * A.T@A)

#reduce the rank
A[:,-1] = A[:,-2]

# shift amount
l = 0.01

#new matrix
B = A + l*np.eye(m,m)

#print
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))


29
30


### code challenge: is this vector in span of this set?

In [ ]:
# determine whether this vector
v = np.array([[1,2,3,4]]).T #column vector banako

# sapan of this set?
S = np.vstack([[4,3,6,2],[0,4,0,1]]).T # matrix with columns
T = np.vstack([[1,2,2,2],[0,0,1,2]]).T
print(v.shape)
print(S)
print(T)

Sv = np.concatenate((S,v), axis=1)
Tv = np.concatenate((T,v),axis=1)
print(Sv)
print(Tv)

print(np.linalg.matrix_rank(Sv)) # Rank increased:hence, v is not spanned in the set(v is adding new info into matrix)
print(np.linalg.matrix_rank(Tv)) # Rank is constant:hence, v is spanned in the set

(4, 1)
[[4 0]
 [3 4]
 [6 0]
 [2 1]]
[[1 0]
 [2 0]
 [2 1]
 [2 2]]
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]
3
2
