In [2]:
import torch

# 1.Create Tensor

In [13]:
#build a tensor
matrix = torch.tensor([[1.,2.,3.],
                       [4.,5.,6.]],
                      dtype=torch.float32,
                      device='cuda:0',
                      requires_grad=True)
matrix, matrix.device

(tensor([[1., 2., 3.],
         [4., 5., 6.]], device='cuda:0', requires_grad=True),
 device(type='cuda', index=0))

In [131]:
#random tensor
random_tensor = torch.rand(2,3)
random_tensor,random_tensor.dtype

(tensor([[0.0979, 0.4611, 0.0148],
         [0.7496, 0.9510, 0.7114]]),
 torch.float32)

In [132]:
#arange
arange_tensor = torch.arange(0,100,10)
arange_tensor,arange_tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [31]:
#ones
ones_tensor = torch.ones(2,3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
#zeros
zeros_tensor = torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# 2.Tensor Attributes

* dtype
* ndim
* shape / size()
* device

💣 Be careful: right datatype, shape & device

In [10]:
random_tensor.dtype, random_tensor.ndim,random_tensor.shape, random_tensor.shape[0], random_tensor.shape[-1],random_tensor.size(),random_tensor.device

(torch.float32,
 2,
 torch.Size([2, 3]),
 2,
 3,
 torch.Size([2, 3]),
 device(type='cpu'))

# 3.Manipulating Tensors

* Addition
* Substraction
* Division
* Multiplication (element-wise)
* Matrix - Mul


## 1.Mathmatical Operations

In [17]:
tensor1 = torch.rand(2,3)
tensor1

tensor([[0.3420, 0.5177, 0.2207],
        [0.3656, 0.1593, 0.5512]])

In [18]:
#add
tensor1 +10

tensor([[10.3420, 10.5177, 10.2207],
        [10.3656, 10.1593, 10.5512]])

In [19]:
#substract
tensor1 - 10

tensor([[-9.6580, -9.4823, -9.7793],
        [-9.6344, -9.8407, -9.4488]])

In [20]:
#division
tensor1 / 10

tensor([[0.0342, 0.0518, 0.0221],
        [0.0366, 0.0159, 0.0551]])

In [21]:
# Elementwise mul
tensor1 * 10

tensor([[3.4204, 5.1770, 2.2074],
        [3.6559, 1.5931, 5.5116]])

In [28]:
# Dot product (Mat mul)--- @ or torch.matmul or torch.tensordot
tensor1 @ tensor1.T , torch.matmul(tensor1,tensor1.T),torch.tensordot(tensor1,tensor1.T,dims=1)

(tensor([[0.4337, 0.3292],
         [0.3292, 0.4628]]),
 tensor([[0.4337, 0.3292],
         [0.3292, 0.4628]]),
 tensor([[0.4337, 0.3292],
         [0.3292, 0.4628]]))

## 2.Aggregating tensor (Statistical Operation)

* Min
* Max
* Mean
* sum
* var
* *std*

In [39]:
tensor2 = torch.arange(0,100,10)
tensor2,tensor2.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [48]:
# min
torch.min(tensor2), tensor2.min()

(tensor(0), tensor(0))

In [49]:
# max
torch.max(tensor2),tensor2.max()

(tensor(90), tensor(90))

In [45]:
# mean (we need correct datatype) Alert!
torch.mean(tensor2.type(torch.float32)), tensor2.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [50]:
# sum
torch.sum(tensor2),tensor2.sum()

(tensor(450), tensor(450))

In [54]:
# var
torch.var(tensor2.type(torch.float32)),tensor2.type(torch.float32).var()

(tensor(916.6667), tensor(916.6667))

In [55]:
# std
torch.std(tensor2.type(torch.float32)),tensor2.type(torch.float32).std()

(tensor(30.2765), tensor(30.2765))

## 3.Positional min and max

In [56]:
# argmin (returns index of min value)
tensor2.argmin()

tensor(0)

In [57]:
# argmax (returns index of max value)
tensor2.argmax()

tensor(9)

## 4.Reshaping, viewing, stacking, Squeeze, Unqueeze, Permute

* Reshape tensor
* View of tensor is returned but keep same memory as original tensor
* Stacking - combine multiple tensors along new dimension (vstack /hstack)
* Squeeze - removes all '1' dimension from tensor
* Unsqueeze - add '1' dimension to a tensor
* Permute - Retuen view of input with dimensions permuted(swapped) in a certain way


In [58]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [65]:
# Reshape - add extra dimension (size must be compatible)
x_reshaped = x.reshape(9,1) # added one dimension (oth dimension or last dim)
x_reshaped, x_reshaped.shape, x.reshape(3,3), x.reshape(1,9)

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [66]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# changing z changes x (because they share same memory)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [71]:
# stack
x_stacked = torch.stack([x,x,x,x],dim=0) #dim=0 is vstack || dim=1 is hstack
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [74]:
# Squeeze
x_squeezed = torch.squeeze(x_reshaped)
x_squeezed,x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [78]:
# Unsqueeze
x_unsqueezed = torch.unsqueeze(x_squeezed,dim=-1)
x_unsqueezed,x_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [93]:
# Permute - rearranges the dimensions of the target tensor in a specified order
x_original = torch.rand(size=(224,224,3))
print(f'Original shape: {x_original.shape}')
x_permute = torch.permute(x_original,dims=(2,0,1))
print(f'Permuted Shape: {x_permute.shape}')

Original shape: torch.Size([224, 224, 3])
Permuted Shape: torch.Size([3, 224, 224])


# 4.Indexing

In [94]:
# create tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [95]:
x[0] #index first dim (dims = 0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [96]:
x[0][0] #index middle dim (dims = 1)

tensor([1, 2, 3])

In [97]:
x[0][0][0] # index last dim (dims = 2)

tensor(1)

In [98]:
x[:,0]

tensor([[1, 2, 3]])

In [99]:
x[:,:,1] #all values of 0th and 1st dimension but only index 1 of 2nd dimension

tensor([[2, 5, 8]])

In [112]:
x[:,1,1]

tensor([5])

In [113]:
x[0,0,:]

tensor([1, 2, 3])

In [116]:
x[:,2,2]

tensor([9])

In [101]:
x[:,:2,2]

tensor([[3, 6]])

In [120]:
x[:,2,1:3]

tensor([[8, 9]])

# 5.Pytorch & numpy

* default datatype
 - numpy = int64/float64
 - pytorch = int64/float32
 - tensorflow = int32/float32

* They don't share memory.

In [126]:
#numpy to tensor
import numpy as np
n_array = np.arange(1.,8.)
tensor_ = torch.from_numpy(n_array)

n_array,n_array.dtype,tensor_, tensor_.dtype #pytorch reflects numpy default datatype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

In [128]:
#tensor to numpy
new_array = tensor_.numpy()
new_array, new_array.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

# 6.Reproducibility

**Neural Network workflow**
 - start with random numbers
 - tensor operations
 - update random numbers and try to make better representation of the data
 - again
 - again
 - again ...

**Random Seed**
 - to reduce randomness in NN
 - Flavours the randomness

In [135]:
#create two random tensors (unreproducable)
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

random_tensor_A, random_tensor_B, random_tensor_A==random_tensor_B

(tensor([[0.2155, 0.6673, 0.5300, 0.2505],
         [0.1198, 0.6568, 0.8651, 0.4980],
         [0.4668, 0.8498, 0.7571, 0.4677]]),
 tensor([[0.0851, 0.1357, 0.6744, 0.4119],
         [0.9835, 0.6219, 0.7101, 0.6354],
         [0.6322, 0.0069, 0.6451, 0.3155]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [138]:
#create two random tensors (reproducable)
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)#works only for next line
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

random_tensor_C, random_tensor_D, random_tensor_C==random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

#7.Check GPU

In [139]:
!nvidia-smi #device name

Mon Jun 26 11:01:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   74C    P0    30W /  70W |    121MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [140]:
#check GPU access with pytorch

torch.cuda.is_available()

True

In [141]:
# setup device agnostic code

device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [142]:
# count number of devices
torch.cuda.device_count()

1

## Putting tensors and models on GPU


In [145]:
# Putting tensors and models on GPU
# create tensor

tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [146]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device) #setup mathi xa
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [153]:
# Move back to cpu
tensor_back_to_cpu = tensor_on_gpu.to(device='cpu')
#method 2
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()

tensor_back_to_cpu

array([1, 2, 3])