In [1]:
import torch

In [39]:
input = torch.tensor([[[1.,0.,1.,0.],
                     [0.,1.,0.,1.],
                     [1.,0.,1.,0.],
                     [0.,1.,0.,1.]]])
input, input.shape

(tensor([[[1., 0., 1., 0.],
          [0., 1., 0., 1.],
          [1., 0., 1., 0.],
          [0., 1., 0., 1.]]]),
 torch.Size([1, 4, 4]))

In [33]:
inp = torch.randn(1,1,4,4)
inp

tensor([[[[ 0.4755,  0.8696, -0.7003, -0.7234],
          [-0.0666, -0.5618,  1.0350, -0.8542],
          [ 1.7642, -0.2270,  1.2038, -1.7775],
          [-0.7719, -0.6116,  1.4382,  0.4948]]]])

In [58]:
m = torch.nn.Conv2d(in_channels=1, out_channels=2, kernel_size=2, stride=(1,2), padding=1, padding_mode='zeros')


In [55]:
m.parameters

<bound method Module.parameters of Conv2d(1, 2, kernel_size=(2, 2), stride=(1, 2))>

In [56]:
m.weight, m.bias

(Parameter containing:
 tensor([[[[-0.1625, -0.3999],
           [ 0.0881,  0.0642]]],
 
 
         [[[ 0.3618, -0.2580],
           [-0.2408, -0.0924]]]], requires_grad=True),
 Parameter containing:
 tensor([-0.0822, -0.3977], requires_grad=True))

In [52]:
m.weight.data, m.weight.shape

(tensor([[[[ 0.3111, -0.4917],
           [-0.2493, -0.3431]]],
 
 
         [[[ 0.4451, -0.1248],
           [-0.1745, -0.1232]]]]),
 torch.Size([2, 1, 2, 2]))

In [60]:
feature_map = m(input)
feature_map

tensor([[[ 0.2982,  0.2982,  0.4125],
         [ 0.8386,  0.7266,  0.3005],
         [ 0.2982,  0.3575,  0.4718],
         [ 0.8386,  0.7266,  0.3005],
         [ 0.4125,  0.4718,  0.4718]],

        [[-0.0772, -0.0772,  0.2870],
         [ 0.5266,  1.0114,  0.7718],
         [-0.0772,  0.2659,  0.6302],
         [ 0.5266,  1.0114,  0.7718],
         [ 0.2870,  0.6302,  0.6302]]], grad_fn=<SqueezeBackward1>)

In [79]:
import torch
import torch.nn.functional as F

# Create a tensor representing your input data
input_data = torch.tensor([
    [1, 2],
    [3, 4],
], dtype=torch.float32).unsqueeze(0).unsqueeze(0)  # Add batch and channel dimensions

# Print the original input size
print("Original input size:", input_data.shape)  # Should be (1, 1, 2, 2)

# Define padding parameters
padding = (1, 1, 1, 1)  # Padding of 2 on each side (left, right, top, bottom)
padding = (2,2,1,1)
# Apply padding using torch.nn.functional.pad with circular mode
padded_input = F.pad(input_data, padding, mode='circular')

# Print the padded input size
print("Padded input size:", padded_input.shape)  # Should be (1, 1, 6, 6)

# Print the padded input tensor
print("Padded input tensor:")
print(padded_input.squeeze().numpy())  # .squeeze() removes batch and channel dimensions for printing


Original input size: torch.Size([1, 1, 2, 2])
Padded input size: torch.Size([1, 1, 4, 6])
Padded input tensor:
[[3. 4. 3. 4. 3. 4.]
 [1. 2. 1. 2. 1. 2.]
 [3. 4. 3. 4. 3. 4.]
 [1. 2. 1. 2. 1. 2.]]
